external_data_config:
  external_data_csv: data/external/sms.tsv

raw_data_config:
  raw_data_csv: data/raw/train.csv
  model_var: ['label', 'message']
  train_test_split_ratio: 0.2
  target: label
  text: message
  random_state: 111
  new_train_data_csv: data/raw/train_new.csv
  label_encoding: {'ham':0, 'spam':1}
  
processed_data_config:
  train_data_csv: data/processed/spam_train.csv
  test_data_csv:  data/processed/spam_test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: model_iteration1
  run_name: random_forest
  registered_model_name: random_forest_model
  remote_server_uri: http://localhost:1234


random_forest:
  max_depth: 35
  n_estimators: 42

count_vectorizer:
  max_features: 5000

model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib