channels:
- conda-forge
dependencies:
- python=3.9.15
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.1
  - cloudpickle==2.2.0
  - lz4==4.2.0
  - psutil==5.9.4
  - scikit-learn==1.1.2
  - typing-extensions==3.7.4.3
name: mlflow-env
